<?php

return [
    'essential-insights-ob3-webinar-series' => [
        'title' => 'Essential Insights from Our OB3 Webinar Series: Readiness, Policy Changes, and Workforce Pell',
        'meta_title' => 'OB3 Webinar Series Insights | FA Solutions Blog',
        'category' => 'Blog',
        'date' => 'July 2, 2026',
        'parent_route' => 'blogs',
        'parent_label' => 'Back to Blogs',
        'intro' => 'To help institutions move from awareness to readiness, FA Solutions hosted a full OB3 webinar series, bringing our own experts together with industry leaders to break down exactly what\'s changing and what to do about it.',
    ],
    'one-big-beautiful-bill-act-higher-education-impacts' => [
        'title' => 'Important Update: Senate-Passed One Big Beautiful Bill Act Key Higher Education Impacts',
        'meta_title' => 'One Big Beautiful Bill Act Impacts | FA Solutions Blog',
        'category' => 'Blog',
        'date' => 'July 15, 2025',
        'parent_route' => 'blogs',
        'parent_label' => 'Back to Blogs',
        'intro' => 'Here is a summary of many of the key provisions relevant to higher education institutions in the "One Big Beautiful Bill Act." This list is not comprehensive but a starting point to begin thinking about the upcoming change.',
    ],
    'webinar-series-compliance-self-care-student-success' => [
        'title' => 'Essential Insights from Our Webinar Series on Compliance, Self-Care, and Student Success',
        'meta_title' => 'Compliance & Student Success Webinars | FA Solutions Blog',
        'category' => 'Blog',
        'date' => 'January 7, 2025',
        'parent_route' => 'blogs',
        'parent_label' => 'Back to Blogs',
        'intro' => 'Staying informed and adaptable is key in the ever-changing landscape of higher education. Our webinars are packed with essential knowledge and strategies to help you thrive in 2025 and beyond.',
    ],
    'navigating-the-fafsa-verification-maze' => [
        'title' => 'Navigating the FAFSA Verification Maze: A Comprehensive Guide for the 2025-2026 Award Year',
        'meta_title' => 'FAFSA Verification Guide 2025-2026 | FA Solutions Blog',
        'category' => 'Blog',
        'date' => 'October 3, 2024',
        'parent_route' => 'blogs',
        'parent_label' => 'Back to Blogs',
        'intro' => 'As the new academic year approaches, students and educational institutions alike must navigate the complex waters of FAFSA verification. The U.S. Department of Education recently published crucial updates for the 2025-2026 award year that warrant close attention.',
    ],
    'fvt-ge-compliance-solutions' => [
        'title' => 'FVT & GE Compliance Solutions for Higher Ed | FA Solutions',
        'meta_title' => 'FVT & GE Compliance Solutions | FA Solutions Blog',
        'category' => 'Blog',
        'date' => 'July 10, 2024',
        'parent_route' => 'blogs',
        'parent_label' => 'Back to Blogs',
        'intro' => 'The new requirements will change financial aid compliance operations and create additional paperwork, but FA Solutions LLC stands ready to recommend the best practices for institutions to help financial aid directors meet student needs and regulatory requirements.',
    ],
    'the-impact-of-hcm2' => [
        'title' => 'The Impact of HCM2: What Financial Aid Professionals Need to Know',
        'meta_title' => 'The Impact of HCM2 | FA Solutions Blog',
        'category' => 'Blog',
        'date' => 'April 22, 2024',
        'parent_route' => 'blogs',
        'parent_label' => 'Back to Blogs',
        'intro' => 'HCM2 (Heightened Cash Management 2) is an alternative method used for institutions to receive and disburse federal funds. When operating under this payment method, schools must credit a student\'s ledger for the Title IV funds they qualify for and confirm the student received credit balances due before submitting a request to receive these funds.',
    ],
    'reduce-the-pain-of-staff-turnover' => [
        'title' => '4 Proven Ways to Reduce the Pain of Staff Turnover in 2024',
        'meta_title' => 'Reduce Staff Turnover in Financial Aid | FA Solutions Blog',
        'category' => 'Blog',
        'date' => 'February 1, 2024',
        'parent_route' => 'blogs',
        'parent_label' => 'Back to Blogs',
        'intro' => 'To mitigate turnover issues, consider an exploratory call with FA Solutions. We serve as a virtual extension of Financial Aid Offices across the U.S., having supported approximately four hundred institutions. The traditional approach of fully outsourcing financial aid is no longer the only option.',
    ],
    'fafsa-evolution-specialized-insight' => [
        'title' => 'FAFSA Evolution: A Year of Specialized Insight for Financial Aid Directors',
        'meta_title' => 'FAFSA Evolution Insights | FA Solutions Blog',
        'category' => 'Blog',
        'date' => 'January 8, 2024',
        'parent_route' => 'blogs',
        'parent_label' => 'Back to Blogs',
        'intro' => 'In 2023, FA Solutions and Education Compliance Management (ECM) embarked on a mission to empower financial aid directors with invaluable insights into the evolving landscape of FAFSA Simplification. Through a series of thought-provoking webinars, these sessions went beyond expertise, providing a profound understanding for institutions navigating the intricacies of financial aid.',
    ],
    'top-blogs-of-2023' => [
        'title' => 'A Year in Review: Our Top Blogs of 2023 and Navigating FAFSA Simplification',
        'meta_title' => 'Top Blogs of 2023 | FA Solutions',
        'category' => 'Blog',
        'date' => 'December 14, 2023',
        'parent_route' => 'blogs',
        'parent_label' => 'Back to Blogs',
        'intro' => 'As we conclude 2023, we extend our appreciation to financial aid directors for being part of this educational journey. Whether unravelling the complexities of FAFSA Simplification or navigating the evolving landscape of higher education administration, we are committed to delivering valuable insights tailored to your financial aid processes.',
    ],
    'dedicated-resources-bursar-operations' => [
        'title' => 'Why Dedicated Resources Might Be the Missing Piece in Your Bursar Operations',
        'meta_title' => 'Dedicated Bursar Resources | FA Solutions Blog',
        'category' => 'Blog',
        'date' => 'November 20, 2023',
        'parent_route' => 'blogs',
        'parent_label' => 'Back to Blogs',
        'intro' => 'In the complex tapestry of higher education institutions, Bursar operations play a pivotal role. They are the gears that keep the financial machinery running smoothly, ensuring the success of your institution.',
    ],
];
